In [22]:
# load .pt model

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import os
import sys
from tensordict.tensordict import TensorDict, TensorDictBase
from torchrl.data import (
    BinaryDiscreteTensorSpec,
    CompositeSpec,
    UnboundedContinuousTensorSpec,
    BoundedTensorSpec,
)


def load_model(model_path):
    model = torch.load(model_path)
    return model


state_dict_path = "model/checkpoint_pwm_track_humm.pt"
state_dict = load_model(state_dict_path)


In [24]:
from omni_drones.learning import ALGOS

algo = ALGOS["ppo"]


observation_spec = CompositeSpec(
            {
                "agents": CompositeSpec(
                    {
                        "observation": UnboundedContinuousTensorSpec(
                            (1, 1, 38), device='cuda:0'
                        ),
                    }
                ),
                "truncated": BinaryDiscreteTensorSpec(
                    1, dtype=bool, device='cuda:0'
                ),
            }
        )

# BoundedTensorSpec(
#     shape=torch.Size([1, 1, 4]),
#     space=ContinuousBox(
#         low=Tensor(shape=torch.Size([1, 1, 4]), device=cuda:0, dtype=torch.float32, contiguous=True),
#         high=Tensor(shape=torch.Size([1, 1, 4]), device=cuda:0, dtype=torch.float32, contiguous=True)),
#     device=cuda:0,
#     dtype=torch.float32,
#     domain=continuous)

action_spec = (
            CompositeSpec(
                {
                    "agents": {
                        "action": BoundedTensorSpec(
                            (1, 1, 4),
                            low=torch.tensor(-1.0, device='cuda:0'),
                            high=torch.tensor(1.0, device='cuda:0'),
                            device='cuda:0',
                            dtype=torch.float32,
                        ),
                    }
                }
            )
            .to('cuda:0')
        )


reward_spec = (
            CompositeSpec({"agents": {"reward": UnboundedContinuousTensorSpec((1, 1))}}).to('cuda:0')
        )


policy = algo(
            'ppo', 
            observation_spec, 
            action_spec, 
            reward_spec, 
            device='cuda:0'
        )

TypeError: BoundedTensorSpec.__init__() got multiple values for argument 'low'

In [ ]:
CompositeSpec(
    agents: CompositeSpec(
        observation: UnboundedContinuousTensorSpec(
            shape=torch.Size([1, 1, 38]),
            space=None,
            device=cuda:0,
            dtype=torch.float32,
            domain=continuous),
        observation_h: UnboundedContinuousTensorSpec(
            shape=torch.Size([1, 1, 38, 32]),
            space=None,
            device=cuda:0,
            dtype=torch.float32,
            domain=continuous),
        intrinsics: CompositeSpec(
            mass: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 1]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous),
            inertia: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 3]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous),
            com: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 3]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous),
            KF: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 4]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous),
            KM: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 4]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous),
            tau_up: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 4]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous),
            tau_down: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 4]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous),
            drag_coef: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 1]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous),
            payload_mass: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 1]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous),
            payload_z: UnboundedContinuousTensorSpec(
                shape=torch.Size([1, 1, 1]),
                space=None,
                device=cuda:0,
                dtype=torch.float32,
                domain=continuous), device=cuda:0, shape=torch.Size([1, 1])), device=cuda:0, shape=torch.Size([1])),
    truncated: BinaryDiscreteTensorSpec(
        shape=torch.Size([1, 1]),
        space=DiscreteBox(n=2),
        device=cuda:0,
        dtype=<class 'bool'>,
        domain=discrete), device=cuda:0, shape=torch.Size([1]))
BoundedTensorSpec(
    shape=torch.Size([1, 1, 4]),
    space=ContinuousBox(
        low=Tensor(shape=torch.Size([1, 1, 4]), device=cuda:0, dtype=torch.float32, contiguous=True),
        high=Tensor(shape=torch.Size([1, 1, 4]), device=cuda:0, dtype=torch.float32, contiguous=True)),
    device=cuda:0,
    dtype=torch.float32,
    domain=continuous)
UnboundedContinuousTensorSpec(
    shape=torch.Size([1, 1, 1]),
    space=None,
    device=cuda:0,
    dtype=torch.float32,
    domain=continuous)


In [14]:
# torch.Size([1, 1, 38])
# tensor([[[-2.9065e-02,  1.9383e-02, -9.8150e-03, -4.5094e-02,  2.5521e-01,
#           -3.9731e-02, -3.3559e-02,  4.9624e-01, -7.2935e-02,  7.2942e-03,
#            7.3375e-01, -1.0886e-01,  4.7575e-01,  1.5833e-01,  4.7201e-01,
#            7.7179e-02,  2.0590e-01,  8.5373e-01, -3.4413e-01,  2.8125e+00,
#           -3.9225e-01, -1.5820e+00, -1.5594e+00, -1.3953e-01, -5.4250e-01,
#            8.3772e-01, -6.2592e-02,  3.2615e-01,  2.7870e-01,  9.0330e-01,
#           -6.8879e-01,  7.2777e-01,  1.2982e-04, -6.5337e-02, -1.0002e+00,
#            4.6406e-01, -5.1299e-01, -1.8665e-01]]], device='cuda:0')
# torch.Size([1, 1, 38, 32])
# tensor([[[[ 0.0053,  0.0043,  0.0030,  ..., -0.0274, -0.0282, -0.0291],
#           [ 0.0263,  0.0247,  0.0230,  ...,  0.0181,  0.0187,  0.0194],
#           [-0.0326, -0.0322, -0.0319,  ..., -0.0113, -0.0105, -0.0098],
#           ...,
#           [-0.6617, -0.1151,  0.1106,  ...,  0.6291,  0.7438,  0.4641],
#           [-1.8886, -0.0219, -0.5064,  ..., -0.9825,  0.4050, -0.5130],
#           [ 0.6582, -0.2834, -0.3345,  ...,  0.1108, -0.7082, -0.1866]]]],
#        device='cuda:0')
# torch.Size([1, 1])
# TensorDict(
#     fields={
#         KF: Tensor(shape=torch.Size([1, 1, 4]), device=cuda:0, dtype=torch.float32, is_shared=True),
#         KM: Tensor(shape=torch.Size([1, 1, 4]), device=cuda:0, dtype=torch.float32, is_shared=True),
#         com: Tensor(shape=torch.Size([1, 1, 3]), device=cuda:0, dtype=torch.float32, is_shared=True),
#         drag_coef: Tensor(shape=torch.Size([1, 1, 1]), device=cuda:0, dtype=torch.float32, is_shared=True),
#         inertia: Tensor(shape=torch.Size([1, 1, 3]), device=cuda:0, dtype=torch.float32, is_shared=True),
#         mass: Tensor(shape=torch.Size([1, 1, 1]), device=cuda:0, dtype=torch.float32, is_shared=True),
#         payload_mass: Tensor(shape=torch.Size([1, 1, 1]), device=cuda:0, dtype=torch.float32, is_shared=True),
#         payload_z: Tensor(shape=torch.Size([1, 1, 1]), device=cuda:0, dtype=torch.float32, is_shared=True),
#         tau_down: Tensor(shape=torch.Size([1, 1, 4]), device=cuda:0, dtype=torch.float32, is_shared=True),
#         tau_up: Tensor(shape=torch.Size([1, 1, 4]), device=cuda:0, dtype=torch.float32, is_shared=True)},
#     batch_size=torch.Size([1, 1]),
#     device=cuda:0,
#     is_shared=True)
# tensor([[[-0.0663,  0.5246, -1.4869, -0.2920]]], device='cuda:0')


OrderedDict([('gae.gamma', tensor(0.9900)),
             ('gae.lmbda', tensor(0.9500)),
             ('actor.module.0.module.0.0.weight',
              tensor([[-0.0020,  0.1073, -0.0310,  ..., -0.0510, -0.0502, -0.0499],
                      [ 0.0697, -0.0858, -0.0636,  ..., -0.1108, -0.1103, -0.1117],
                      [-0.1202,  0.1369,  0.0989,  ..., -0.0371, -0.0359, -0.0369],
                      ...,
                      [-0.1651, -0.0013, -0.0469,  ...,  0.0074,  0.0075,  0.0075],
                      [-0.0463,  0.0281,  0.2107,  ..., -0.0467, -0.0461, -0.0464],
                      [-0.2681,  0.4882,  0.5944,  ...,  0.0022,  0.0013,  0.0021]],
                     device='cuda:0')),
             ('actor.module.0.module.0.0.bias',
              tensor([-2.1497e-01, -2.0213e-01, -1.9858e-01, -1.6965e-01, -1.0283e-01,
                      -2.1809e-01,  1.8970e-02, -2.1120e-01, -1.7792e-01, -1.8926e-01,
                      -2.1211e-01, -1.7853e-01,  8.4836e-03, -1.3665